# Generated by Django 5.1.2 on 2024-12-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_producto', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('volumen', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=100)),
                ('notas_olfativas', models.CharField(max_length=100)),
            ],
        ),
    ]
