# Generated by Django 5.1.2 on 2024-12-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_promocion', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_inicio', models.CharField(max_length=100)),
                ('fecha_fin', models.CharField(max_length=100)),
                ('descuento', models.CharField(max_length=100)),
                ('productos_aplicados', models.CharField(max_length=100)),
                ('condiciones', models.CharField(max_length=100)),
            ],
        ),
    ]
