# Generated by Django 5.1.2 on 2024-12-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_proveedor', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fechadecontratacion', models.CharField(max_length=100)),
            ],
        ),
    ]
