# Generated by Django 5.1.2 on 2024-12-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_pedido', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField()),
                ('fecha_receta', models.CharField(max_length=100)),
                ('total_pedido', models.IntegerField()),
                ('estado_pedido', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('direccion_envio', models.CharField(max_length=100)),
            ],
        ),
    ]
